"""criando_tabela_processos_judiciais

Revision ID: 0a8226c68d18
Revises: 
Create Date: 2026-03-01 19:15:01.583406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8226c68d18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos_judiciais',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único do processo no sistema.'),
    sa.Column('tipo', sa.Enum('CIVEL', 'TRABALHISTA', 'PENAL', 'TRIBUTARIO', name='tipoprocesso'), nullable=False, comment='Classificação da área do direito.'),
    sa.Column('resumo_peticao', sa.Text(), nullable=False, comment='Síntese dos fatos e fundamentos da petição inicial.'),
    sa.Column('valor_pedido', sa.Numeric(precision=10, scale=2), nullable=False, comment='Valor da causa ou do pedido principal em reais (R$).'),
    sa.Column('historico_cliente', sa.String(length=255), nullable=False, comment='Histórico ou perfil do cliente para contextualizar a estratégia da IA.'),
    sa.Column('numero', sa.String(length=50), nullable=False, comment='Número do processo no padrão CNJ.'),
    sa.PrimaryKeyConstraint('id'),
    comment='Armazena os dados principais dos processos judiciais para análise da IA.'
    )
    op.create_index(op.f('ix_processos_judiciais_id'), 'processos_judiciais', ['id'], unique=False)
    op.create_index(op.f('ix_processos_judiciais_numero'), 'processos_judiciais', ['numero'], unique=True)
    op.create_index(op.f('ix_processos_judiciais_tipo'), 'processos_judiciais', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processos_judiciais_tipo'), table_name='processos_judiciais')
    op.drop_index(op.f('ix_processos_judiciais_numero'), table_name='processos_judiciais')
    op.drop_index(op.f('ix_processos_judiciais_id'), table_name='processos_judiciais')
    op.drop_table('processos_judiciais')
    # ### end Alembic commands ###
