"""nova_tabela_mesagem_chat

Revision ID: f1e8d61a9a52
Revises: 4043768e0b0e
Create Date: 2026-03-04 00:21:18.314208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e8d61a9a52'
down_revision: Union[str, Sequence[str], None] = '4043768e0b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['processo_id'], ['processos_judiciais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Armazena o histórico de conversas com a IA especialista.'
    )
    op.create_index(op.f('ix_mensagens_chat_id'), 'mensagens_chat', ['id'], unique=False)
    op.create_index(op.f('ix_mensagens_chat_processo_id'), 'mensagens_chat', ['processo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_chat_processo_id'), table_name='mensagens_chat')
    op.drop_index(op.f('ix_mensagens_chat_id'), table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    # ### end Alembic commands ###
